### PR TITLE
chore: use yarn workspaces for example apps

### PR DESCRIPTION
**Pull request by alexlafroscia**
This updates the repo to use Yarn Workspaces to manage the fact that there are actually a few different packages in this repo.

Essentially, what I did was

1. Move everything related to the library -- including the top-level `package.json` -- into a sub-directory (I called it `storybook-addon-html` but it could be anything. I'm not sure what the best option here is; let me know if you have opinions! Something like `lib` could work well too)
2. Remove the `yarn.lock` files from the example apps
3. Add a root-level `package.json` file that points to the workspaces (anything in `examples`, plus `storybook-addon-html`)
4. Move shared dev-dependencies back up to the root level (ESLint and Prettier; prettier is now both a dev dependency of the whole repository _and_ a dependency of the library, which is a little confusing, but also does make sense!)

Now when you run `yarn install` it installs _everything_ you need to run `yarn start` in either of the `example` apps and you're off to the races

**HTML example**

Screen Shot 2020-08-13 at 7 59 33 PM

**React example**

Screen Shot 2020-08-13 at 7 59 57 PM

### CODE REVIEW

**Comment by alexlafroscia** [comment]
I hope you don't mind, but I went and added a `CONTRIBUTING.md` that explains the directory structure for a new contributor and tells about how to actually build/run the example apps. I left information on publishing a new release out, but especially since the library itself now lives in a sub-directory, that might be useful for someone to fill in later!

**Comment by alexlafroscia** [comment]
One thought on the naming -- maybe the entire library should go in `lib` and then the output from Babel goes in `lib/out`?

That way there isn't an awkward `lib/lib` folder which might be hard to communicate about.

**Comment by jeanfredrik** [comment]
This looks like a great improvement to the folder structure!

I think both `lib/out` and `lib/build` are good options. Which do you prefer? Have you seen this naming pattern in other libraries?

**Comment by jeanfredrik** [comment]
`/addon` or `/package` could also work

**Comment by alexlafroscia** [comment]
Hmm... I think `/addon` actually works nicely here! `lib` works for me too, but `addon` nicely aligns with the way that the Storybook repo itself is structured; all the of the addons are in an `addons` directory.

I think I'll tweak this PR to use `addon/out` and we can take a look at it from there!

**Comment by alexlafroscia** [comment]
Nope! If you're satisfied with it like this, I am too! I'll get the branch for Storybook 6 updated to work with this once it is merged.

**Pull request merged**
