### PR TITLE
42tte/feat support prettier v3

### LINKED ISSUE #104: `Uncaught TypeError: m.trim is not a function` in Storybook v7.1
I’m using your fantastic addon successfully with Storybook 7 Angular, but on Storybook 7.1 (beta) I’m getting following errors:

```
Uncaught TypeError: m.trim is not a function
    Ch http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:59
    renderWithHooks http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    updateFunctionComponent http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    beginWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:71
    callCallback2 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:2
    invokeGuardedCallbackDev http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:2
    invokeGuardedCallback http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:2
    beginWork$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performUnitOfWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    workLoopSync http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performSyncWorkOnRoot http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    unstable_runWithPriority http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:1
    runWithPriority$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueue http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    scheduleUpdateOnFiber http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    enqueueSetState http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:44
    setState http://0.0.0.0:6006/sb-manager/chunk-3FAXWWKG.js:3
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    newState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setAddonState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    useSharedState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    sP http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    Channel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handler http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    PostMessageTransport http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    createBrowserChannel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    ReactProvider http://0.0.0.0:6006/sb-manager/runtime.js:1
    <anonymous> http://0.0.0.0:6006/sb-manager/runtime.js:1
manager-bundle.js:59:848
```

and 

```
Uncaught (in promise) TypeError: can't access property "languages", a is undefined
    n http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:80
    wk http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:80
    ZW http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:80
    Wk http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:90
    yn http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:92
    Mi http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:92
    D http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    updateMemo http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    useMemo http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    useMemo http://0.0.0.0:6006/sb-manager/chunk-3FAXWWKG.js:9
    sP http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    Tabs http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:220
    Tabs http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:220
    renderWithHooks http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    updateFunctionComponent http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    beginWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:71
    beginWork$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performUnitOfWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    workLoopSync http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performSyncWorkOnRoot http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    unstable_runWithPriority http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:1
    runWithPriority$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueue http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    scheduleUpdateOnFiber http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    enqueueSetState http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:44
    setState http://0.0.0.0:6006/sb-manager/chunk-3FAXWWKG.js:3
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    newState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setAddonState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    useSharedState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    sP http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    Channel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handler http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    PostMessageTransport http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    createBrowserChannel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    ReactProvider http://0.0.0.0:6006/sb-manager/runtime.js:1
    <anonymous> http://0.0.0.0:6006/sb-manager/runtime.js:1
2 manager-bundle.js:80:692

```

Maybe it’s dependencies related, but I can’t find out atm what to do.

### PR DESCRIPTION
**Pull request by 42tte**
Fixes #104

### CODE REVIEW

**Comment by Profesor08** [comment]
@whitespace-dev

**Comment by methodev** [comment]
@jeanfredrik

**Comment by 42tte** [comment]
Please have a look at this when you got the time @jeanfredrik It is preventing us, and others, from upgrading Prettier

**Comment by methodev** [comment]
Is this project still alive?

**Comment by prinzt** [comment]
I applied the patch manually to a local Storybook Vue 3 project and the HTML view seems to work fine.

**Comment by methodev** [comment]
> I applied the patch manually for a local Storybook 7.4.1 Vue 3 project and the HTML panel seems to work fine.

How did you make it? Can you give us example?

**Comment by prinzt** [comment]
I just copy/pasted the changes to the files under `node_modules/@whitespace/storybook-addon-html/dist/esm`.
This was only for testing purposes and is of course not a production solution ;)
One could automate this with a patch file for deployment/production until the PR is merged.

**Comment by Profesor08** [comment]
You can use this pachage to manage patches: [npm i patch-package](https://www.npmjs.com/package/patch-package)

**Comment by prinzt** [comment]
@Profesor08 Thanks a lot. I didn't know that one.

**Comment by jonock** [comment]
Would be amazing if the PR can be merged @jeanfredrik . It's currently blocking us on a project...
Thanks for your work!

**Comment by 42tte** [comment]
Would have loved an early Christmas gift 🎅 🎁

**Comment by wigsnes** [comment]
@jeanfredrik Would like this fixed!

**Comment by gavinbarron** [comment]
> I just copy/pasted the changes to the files under `node_modules/@whitespace/storybook-addon-html/dist/esm`. This was only for testing purposes and is of course not a production solution ;) One could automate this with a patch file for deployment/production until the PR is merged.

Great suggestion, I did just this using a patch via yarn for our project that is looking to use this add-on

**Comment by sovanyio** [comment]
@whitespace-dev, created a fork with storybook v7 changes along with the prettier v3 change: https://github.com/sovanyio/storybook-addon-html/tree/feature/sb-v7

Definitely uglier than what @42tte has, but utilizing this directly from my repo for another project. Didn't test the zx scripts or really anything beyond the build/utilization; its not backward compatible--but might be time for a breaking release for sb v7/prettier v3 support? :)

**Comment by Ollitod** [comment]
@jeanfredrik please accept the PR. Since we use Angular 17 and the new control flow syntax, we need to use Prettier 3.1 to be able to format the code according to the new rules. This is definitely a blocker for any Angular 17 project. See #110.

**Comment by JamesIves** [comment]
Seems like this project hasn't been updated in almost two years 😞

**Comment by jaydeep987** [comment]
Unbelievable, again such issue with storybook ecosystem... always blocks some other upgrades just because such PRs never gets merged and deps version are far behind.

**Comment by jeanfredrik** [comment]
Hello everyone!
Sorry for not taking a look at this. I will look into it now.

**Comment by jeanfredrik** [comment]
We just released version 6.0.0 which uses Storybook 8 and Prettier 3. Please try to update to the latest version and see if everything works. Create new issues if they are not.

**Pull request closed without merging**
